### ISSUE TITLE
influx write --format csv fails silently if a file has incompatible line endings

### ISSUE THREAD

**Issue by russorat** [influxdata/influx-cli#106]
I have a csv file that came from a windows machine, and i am trying to use the `influx write dryrun` command on my mac to load the data into influxdb.

here is the bad file: 
[bad_line_endings.csv](https://github.com/influxdata/influx-cli/files/6562065/bad_line_endings.csv)

And here is the output trying to load it, which does nothing and gives no indication there is a problem.
```
➜  darwin git:(master) ✗ ./influx write dryrun -f /Users/rsavage/Downloads/bad_line_endings.csv  --format csv --debug --skipRowOnError
2021/05/28 09:14:03 WriteFlags{genericCLIOpts:{in:0xc000010010 w:0xc000010018 errW:0xc000010020 viper:0xc00049ed80 json:false hideHeaders:false runEWrapFn:0x4dd4c40} globalFlags:0x6d34600 svcFn:0x4dced40 org:{id: name:} BucketID: Bucket: Precision:ns Format:csv Headers:[] Files:[/Users/rsavage/Downloads/bad_line_endings.csv] URLs:[] Debug:true SkipRowOnError:true SkipHeader:0 MaxLineLength:16000000 IgnoreDataTypeInColumnName:false Encoding:UTF-8 ErrorsFile: RateLimit: Compression:} args:[]
```

Then, i ran the bad_line_endings.csv file through the `dos2unix` command:
`dos2unix -n ~/Downloads/bad_line_endings.csv ~/Downloads/good_line_endings.csv`

Which produced this file: 
[good_line_endings.csv](https://github.com/influxdata/influx-cli/files/6562073/good_line_endings.csv)

Running this file with the same configuration gave results:
```
➜  darwin git:(master) ✗ ./influx write dryrun -f /Users/rsavage/Downloads/good_line_endings.csv  --format csv --debug --skipRowOnError
2021/05/28 09:14:06 WriteFlags{genericCLIOpts:{in:0xc000010010 w:0xc000010018 errW:0xc000010020 viper:0xc00049ca20 json:false hideHeaders:false runEWrapFn:0x4dd4c40} globalFlags:0x6d34600 svcFn:0x4dced40 org:{id: name:} BucketID: Bucket: Precision:ns Format:csv Headers:[] Files:[/Users/rsavage/Downloads/good_line_endings.csv] URLs:[] Debug:true SkipRowOnError:true SkipHeader:0 MaxLineLength:16000000 IgnoreDataTypeInColumnName:false Encoding:UTF-8 ErrorsFile: RateLimit: Compression:} args:[]
2021/05/28 09:14:06 CsvTable{ dataColumns: 5 constantColumns: 0
 measurement: &{Label:m DataType:measurement DataFormat: LinePart:2 DefaultValue: Index:4 TimeZone:UTC ParseF:<nil> ComputeValue:<nil> escapedLabel:}
 tag:         &{Label:parent DataType:tag DataFormat: LinePart:3 DefaultValue: Index:2 TimeZone:UTC ParseF:<nil> ComputeValue:<nil> escapedLabel:parent}
 field:       &{Label:sensor_id DataType:string DataFormat: LinePart:0 DefaultValue: Index:1 TimeZone:UTC ParseF:<nil> ComputeValue:<nil> escapedLabel:sensor_id}
 field:       &{Label:average DataType:double DataFormat: LinePart:0 DefaultValue: Index:3 TimeZone:UTC ParseF:<nil> ComputeValue:<nil> escapedLabel:average}
 time:        &{Label:time DataType:dateTime DataFormat:number LinePart:5 DefaultValue: Index:0 TimeZone:UTC ParseF:<nil> ComputeValue:<nil> escapedLabel:}
}
test,parent=2nd\ Floor\ Open\ Plan\ DS sensor_id="xx:xx:xx:xx:xx:xx",average=0 1549240000000000000
test,parent=2nd\ Floor\ Open\ Plan\ DS sensor_id="xx:xx:xx:xx:xx:xx",average=0 1549240000000000000
test,parent=2nd\ Floor\ High\ Table\ 1 sensor_id="xx:xx:xx:xx:xx:xx",average=0 1549240000000000000
test,parent=2nd\ Floor\ Open\ Plan\ DS sensor_id="xx:xx:xx:xx:xx:xx",average=0 1549240000000000000
```

My expectation is that when the `influx write` command has trouble parsing a csv file because of the line endings, there is some sort of message to the user guiding them in the right direction.

**Comment by danxmoran** [comment]
Some more data for future me (or anyone else who works on this):
```
$ file bad_line_endings.csv
bad_line_endings.csv: ASCII text, with CR line terminators
```

I'd expect to see `CRLF` terminators from most Windows machines, so the impact of whatever's going on might be limited. We're probably hitting golang/go#7802, which was effectively closed as a "won't fix". There's a work-around linked in the comment thread there that might help us address the problem on our end.

**Comment by sranka** [comment]
Golang's CSV reader supports and recognizes properly both UNIX (\n) and Windows (\r\n) line endings. The bad_line_endings.csv file has however very exotic line endings: \r\r\r. The whole file is then read as a single header line and the tool then runs silently with no action since no data lines are in fact available. As a solution, the tool can possibly detect such situations and warn the user.  @danxmoran if you are ok with it, I'd be glad to improve the code that I originally created.

**Comment by danxmoran** [comment]
@sranka that would be great, thank you! The high-level layout of the code changed when we migrated it to this repo, but the core structure should be identical to what is/was in `influxdb`
