### ISSUE TITLE
`influx dashboards` doesn't work when `--org` is specified

### ISSUE THREAD

**Issue by yzhang1991** [influxdata/influx-cli#108]
__Steps to reproduce:__
1. Initialize an influxdb OSS instance locally (I use OS X), create an organization and a bucket. For my case, I did the initialization using the http://localhost:9999 UI.
2. While the OSS is running, try to access the database using `influx repl` command:
```
➜  influxdb git:(master) influx repl -o "my-org"
Error: Unable to find organization: organization not found.
```
3. Go to the web UI, find the organization Id for "my-org", try again access the database by using the organization id:
```
➜  influxdb git:(master) influx repl --org-id 047e8606a2268000
>
```
This works.

__Expected behavior:__
The `-o` flag with the organization name should work the same as the organization id.

__Actual behavior:__
Only organization id works.

__Environment info:__

* System info: Run `uname -srm` and copy the output here
  Darwin 19.0.0 x86_64
* InfluxDB version: Run `influxd version` and copy the output here
  2.0.0 (cde064b)
  **Note**: `influxd version` does not work:
```
➜  influxdb git:(master) influxd version
Error: unknown command "version" for "influxd"
Run 'influxd --help' for usage.
```

**Comment by danxmoran** [comment]
I've updated the title to reflect the latest comment from @Tristan107. The earlier comments are no longer relevant now that the `repl` command has been deleted.
