### ISSUE TITLE
Cleanup duplicate logic for acquiring Organization ID

### ISSUE THREAD

**Issue by DStrand1** [influxdata/influx-cli#132]
There is a lot of duplicate logic for acquiring the organization ID from passed in `OrgParams`. There are two main situations that "business logic" for commands has to deal with this:
### Has an embedded `OrganizationsApi`:
This case is relatively simple, and can cleanup the logic with a method along the lines of:
```go
func (o OrgParams) GetOrgID(ctx context.Context, api api.OrganizationsApi, defaultOrg string) (string, error) {
    ...
}
```
where `defaultOrg` is intended to be passed in from the `ActiveConfig`, unless special logic demands it be different.

### Does not have an embedded `OrganizationsApi`:
My first thought for this was having an interface like:
```go
type <T> OrgHolder interface {
    Org(string) T
    OrgID(string) T
}

func (o OrgParams) <T> GetOrgID(defaultOrg string) T {
    ...
}
```
since other embedded api's that allow search by OrgName or OrgID will have these two API methods. However clearly we cannot do this, since Go currently lacks generics. This case is more difficult to solve, and will need some thought/discussion.

**Comment by lesam** [comment]
Closed by https://github.com/influxdata/influx-cli/pull/272
