### ISSUE TITLE
Allow setting membership type in `influx org members add`

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influx-cli#231]
`influx org members add` is hard-coded to add new users to an org as a "member". We should add a way for users to be added as an "owner" (the API already supports this, so we need to add a toggle to the CLI).

`influx org members list` and `influx org members remove` may also need to be updated to account for owners as well as members.

**Comment by lesam** [comment]
Until this is implemented, you can get effectively the same thing by granting a user an all-access token on the org, since users inherit the permissions of all the tokens that the own:

```
influx auth create --all-access -u <userNeedingPermission> -o <theorg>
```

**Comment by kuzyn** [comment]
Is it possible to link on how to do this with the API?

**Comment by glacieruk** [comment]
What release is this in?

**Comment by samhld** [comment]
@glacieruk it hasn't been released yet. Next release!
