### ISSUE TITLE
Detect when users are trying to access the 1.x REPL, and return an explicit error

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influx-cli#329]
A common question we see from users migrating from 1.x is "how do I find the REPL?". We should detect when users are trying to access the REPL and return a clear error, ideally guiding the user towards the 2.x UI for interactive queries.

**Comment by Anaisdg** [comment]
But maybe also add a link in the error message to docs on how to build the repl. There are some use cases for it (like wanting to write csv form a local file with flux).

**Comment by lesam** [comment]
See issues above to add the REPL's back to the CLI - maybe we get those done soon enough this is unecessary?

**Comment by candrewlee14** [comment]
We now have a REPL again using `influx v1 repl`, merged in #386. 
Should running `influx` hint to the user something like `NOTE: If you're looking for the 1.x REPL, try "influx v1 repl"` or something like that?
