### ISSUE TITLE
`apply` with `-e jsonnet` fails

### ISSUE THREAD

**Issue by wbaker85** [influxdata/influx-cli#351]
Applying a `jsonnet` template causes an error when using the CLI with a cloud host, and will soon cause an error with an OSS host: https://github.com/influxdata/influxdb/pull/23030

To reproduce, the file at https://github.com/influxdata/influxdb/blob/master/pkger/testdata/bucket_associates_labels.jsonnet can be used with  `influx apply -e jsonnet -f bucket_associates_labels.jsonnet` with the file saved locally, or even `influx apply -e jsonnet -u https://github.com/influxdata/influxdb/blob/master/pkger/testdata/bucket_associates_labels.jsonnet` for a hosted file.

Since server-side jsonnet parsing is now disabled, we will need to parse it in the client to be able to handle jsonnet templates.

**Comment by DStrand1** [comment]
The CLI does seem to be able to parse `jsonnet` templates, the error seems to be somewhere else. If you run the command listed above as:
```
cat ./bucket_associates_labels.jsonnet | influx apply -e jsonnet
```
it works as expected and causes no issues. So I think this issue is something else other than the server losing `jsonnet` parsing abilities
