### ISSUE TITLE
'influx user create' adds user to both 'owners' and 'members'

### ISSUE THREAD

**Issue by jdstrand** [influxdata/influx-cli#352]
Steps to reproduce:
```
$ influx user create -n foo@example.com -o dev -skip-verify
ID			Name
08ca5fdf4c76d000	foo@example.com
$ curl --insecure -H "Authorization: Token $TOKEN" --request GET $URL/api/v2/orgs/$ORGID/members
{
	"links": {
		"self": "/api/v2/orgs/.../members"
	},
	"users": [
		{
			"role": "member",
			"links": {
				"self": "/api/v2/users/08ca5fdf4c76d000"
			},
			"id": "08ca5fdf4c76d000",
			"name": "foo@example.com",
			"status": "active"
		}
	]
}

$ curl --insecure -H "Authorization: Token $TOKEN" --request GET $URL/api/v2/orgs/.../owners
{
	"links": {
		"self": "/api/v2/orgs/.../owners"
	},
	"users": [
		{
			"role": "owner",
			"links": {
				"self": "/api/v2/users/08ca215f1576d000"
			},
			"id": "08ca215f1576d000",
			"name": "orgdfd3ced56dbd2ae7-user-11618",
			"status": "active"
		}
	]
}
```

Two things:
* the UI appears to default to `member` when the user id is in both `members` and `owners` which is read-only and not the expected UI experience
* the `name` in `owners` is wrong. I tested this against a remocal (cloud 2) test deployment, but it is odd that the `name` is correct in `members` and wrong in `owners`

This can be worked around with `influx org members remove --member 08ca5fdf4c76d000 --id $ORGID` after creating the user.

Assuming that adding the new user to `owners` by default is desirable, it may make sense to add a `--member` switch to `influx user create` so that users can opt into changing that behavior. Also see https://github.com/influxdata/influx-cli/issues/353

**Comment by wbaker85** [comment]
Is it the same user in both members and owners? The name is different, but also the user ID is different.

We've gotten this question from OSS users quite a bit, and the workaround requires adding the user as an org owner, and removing them as a member, so I wonder if there is a server-side difference? See: https://community.influxdata.com/t/creating-admin-users-in-influxdb-2-oss/19754

Running a similar set of commands on OSS I get this:
```
influx user create -n foo@example.com -o dev -skip-verify
ID			Name
08ce9235bbcb7000	foo@example.com
```

```
curl --insecure -H "Authorization: Token $TOKEN" --request GET $URL/api/v2/orgs/$ORGID/members
{
	"links": {
		"self": "/api/v2/orgs/0dd41d155f728187/members"
	},
	"users": [
		{
			"role": "member",
			"links": {
				"self": "/api/v2/users/08ce9235bbcb7000"
			},
			"id": "08ce9235bbcb7000",
			"name": "foo@example.com",
			"status": "active"
		}
	]
}
```

```
{
	"links": {
		"self": "/api/v2/orgs/0dd41d155f728187/owners"
	},
	"users": [
		{
			"role": "owner",
			"links": {
				"self": "/api/v2/users/08c7d22929c16000"
			},
			"id": "08c7d22929c16000",
			"name": "wbaker",
			"status": "active"
		}
	]
}
```

Note that the org owner is a different user than the org member - and the org member is actually my operator account that I used to create the organization.

**Comment by jdstrand** [comment]
Hrmm, I can confirm the behavior you are seeing. The user was only added to members and not owners. I must've done something weird locally and then was too hasty in writing my reproducer. Thanks for double-checking and sorry for the noise. Closing.

**Comment by wbaker85** [comment]
I could see it happening if you create an org with a user, and then add that same user as a member to the org. It would then be both a member and an owner. Haven't tested that though, so maybe it doesn't work.
