### ISSUE TITLE
feature: add 'influx org owners' command

### ISSUE THREAD

**Issue by jdstrand** [influxdata/influx-cli#353]
`influx` lacks a way to add users as owners of the org and people must use `/api/v2/orgs/ORGID/owners` directly. Today `influx user create` puts users in `/api/v2/orgs/ORGID/members` by default, which is more secure but makes the UI difficult to use. It would be good to have an `influx orgs owners` command the operates like `influx orgs members` so that users can move people around. `influx user create` might want to gain an `--owner` switch to change the default behavior (or something similar).

**Comment by wbaker85** [comment]
Possible duplicate? https://github.com/influxdata/influx-cli/issues/231

**Comment by lesam** [comment]
Closing this as a duplicate
