### ISSUE TITLE
influx delete predicate doesn't work with all admissible characters

### ISSUE THREAD

**Issue by francotiveron** [influxdata/influx-cli#388]
```
// @ in predicate -> error, note that @ is legal and working
> influx delete --bucket tick --start '1677-09-21T00:12:43.145224194Z' --stop '2262-04-11T23:47:16.854775806Z' --predicate '_measurement="EP@2500"'

Error: failed to delete data: 400 Bad Request: invalid request; error parsing request json: bad logical expression, at position 15
```
```
// @ removed -> no error
> influx delete --bucket tick --start '1677-09-21T00:12:43.145224194Z' --stop '2262-04-11T23:47:16.854775806Z' --predicate '_measurement="EP2500"'
```

**Comment by candrewlee14** [comment]
I'm currently unable to reproduce your issue here.
I can create a measurement with an `@` in the name, then run the `influx delete` command successfully.
Then I checked that the data was actually deleted and it was.

What version of influxd are you running? I've got 2.2.0.

<img width="1243" alt="Screen Shot 2022-06-16 at 12 37 29 PM" src="https://user-images.githubusercontent.com/32912555/174142219-f7ffcb07-2d73-4777-a273-9fc8a9bbd701.png">

**Comment by jeffreyssmith2nd** [comment]
@krystufe What version of the CLI are you using? I have no problems with the first command line you provided, and I would expect most of the others to fail for the given error messages that you're seeing.

**Comment by krystufe** [comment]
@jeffreyssmith2nd I am using the latest version (2.6.1) for Windows. What is yours?

**Comment by jeffreyssmith2nd** [comment]
I was using MacOS, but I also tested 2.6.1 on Windows as well with no issues. I don't know if it affects things, but I tested on the new Windows Terminal with both Windows PowerShell and PowerShell (OSS).

**Comment by krystufe** [comment]
@jeffreyssmith2nd thanks for tip.
I tried it in Windows Command Prompt and PowerShell and second works.
Command Prompt:
`C:\Program Files\InfluxData\influx>influx version
Influx CLI 2.6.1 (git: 61c5b4d) build_date: 2022-12-29T15:41:09Z

C:\Program Files\InfluxData\influx>influx delete --bucket VRPR --start 2022-01-01T00:00:00Z --stop 2023-01-01T00:00:00Z --predicate '_measurement="VehicleDwellCounts"'
Error: failed to delete data: 400 Bad Request: error decoding json body: bad logical expression, at position 0`
PowerShell:
`PS C:\Program Files\InfluxData\influx> ./influx version
Influx CLI 2.6.1 (git: 61c5b4d) build_date: 2022-12-29T15:41:09Z
PS C:\Program Files\InfluxData\influx> ./influx delete --bucket VRPR --start 2022-01-01T00:00:00Z --stop 2023-01-01T00:00:00Z --predicate '_measurement="VehicleDwellCounts"'`

**Comment by jeffreyssmith2nd** [comment]
@krystufe Thanks for figuring that out, I've updated the docs to recommend PowerShell usage. https://github.com/influxdata/docs-v2/pull/4693
