### ISSUE TITLE
`influx replication delete` does not recognize the ID of the created replication stream and hence doe not delete it

### ISSUE THREAD

**Issue by shantanoo-desai** [influxdata/influx-cli#426]
## Description
I am currently running some simple EDR (Edge Data Replication) tests on some industrial hardware and I am unable to delete a previously create replication stream

### Environment

- InfluxDB container : `2.3-alpine` / flavor `OSS`
- Within the docker container `influx` CLI: `Influx CLI 2.3.0 (git: 88ba346) build_date: 2022-04-06T19:30:53Z`

### Problem reproduction

I am trying to replicate a simple bucket (where data for the CPU of the machine is stored in a bucket called `data`). The data is to be replicated from one industrial machine to another (both identical)

1. add a remote machine information using:
    
    ```bash
     influx remote create --name=mach2 --remote-url=http://192.30.4.108:8086 --remote-api-token=customAdminToken --remote-org-id=600acd40df42bc62
    ```
2. Create a one-to-one replication stream using:
    ```bash
    ```
3.

**Comment by jeffreyssmith2nd** [comment]
Looks like #427 is the completed version of this, closing in favor of that issue.
