### ISSUE TITLE
Clarify difference in virtual vs. physical DBRPs when listing

### ISSUE THREAD

**Issue by candrewlee14** [influxdata/influx-cli#438]
Virtual DBRPs do not behave like physical DBRPs. Most importantly, they are read-only.
If a user sees the virtual DBRPs in the current list format of `influx v1 dbrp list`, they might not realize that they are immutable.
Separating the list table into two, physical DBRPs and virtual DBRPs, would make the behavior difference more clear to users.

**Comment by sanderson** [comment]
Add to the `influx v1 dbrp list -h` output:

> Virtual DBRP mappings (InfluxDB OSS only) are created automatically using the bucket name. Virtual mappings are read-only. To modify a virtual DBRP mapping, create a new, explicit DBRP mapping. For more information, see https://docs.influxdata.com/influxdb/latest/query-data/influxql/dbrp/

**Comment by samhld** [comment]
<img width="843" alt="image (25)" src="https://user-images.githubusercontent.com/4852912/184982328-3f7860ed-830e-4d65-ac33-75216947b0f3.png">
