### ISSUE TITLE
Potential Windows compatability issue

### ISSUE THREAD

**Issue by peterreg** [influxdata/influx-cli#443]
The following was reported via Docs Feedback for this page:
https://docs.influxdata.com/influxdb/cloud/tools/influx-cli/

Feedback: "The exe file to install CLI for Windows does NOT work with me (in Windows11)"

**Comment by jeffreyssmith2nd** [comment]
Is there any more info on what isn't working? Just tested it on Windows 11 and it seems to be working as expected.

**Comment by peterreg** [comment]
Hi Jeffrey, That is the only information. I'm going to close it
