### ISSUE TITLE
unable to delete a secret - 405 Method Not Allowed:

### ISSUE THREAD

**Issue by andrewbierbaum** [influxdata/influx-cli#468]
__Steps to reproduce:__
1. update and then attempt delete the a secret
```
18:06 andrewbierbaum@host:~$ sudo influx secret update -k testing -v asdf
Key	Organization ID
testing	335d31413785462f
18:06 andrewbierbaum@host:~$ sudo influx secret delete -k testing
Error: failed to delete secret with key "testing": 405 Method Not Allowed:
````

__Expected behavior:__
the key should delete with the same credentials as it should create with

__Actual behavior:__
it returns `405 Method Not Allowed:`

__Environment info:__

* System info: `Linux 4.15.0-192-generic x86_64`
* InfluxDB version: confirmed on both `InfluxDB v2.4.0 (git: de247bab08) build_date: 2022-08-18T19:41:15Z` and `InfluxDB v2.5.1 (git: 5b6fdbf05d) build_date: 2022-11-02T18:06:28Z`
* Other relevant environment details: ubuntu VM

__Config:__
```
18:19 andrewbierbaum@host:~$ sudo cat /root/.influxdbv2/configs
[default]
  url = "http://localhost:8086"
  token = "REDACTED"
  org = "REDACTED"
  active = true
```

**Comment by FernandoBenayas** [comment]
Hey @jeffreyssmith2nd thank **you** for transferring the issue! Just created the PR
