### ISSUE TITLE
Please bump golang.org/x/sys dependency to make the port build on riscv64

### ISSUE THREAD

**Issue by clausecker** [influxdata/influx-cli#482]
The current version of golang.org/x/sys used is too old to support riscv64-freebsd.  Please bump it to `v0.6.0` so the build succeeds there.

**Comment by jeffreyssmith2nd** [comment]
Hey @clausecker, I don't have a good way to test this. Would you be willing to submit a PR with all the changes needed to get a working riscv64 build? My assumption is that it might take more than just that one version bump, but I could be wrong in that assumption.

**Comment by clausecker** [comment]
As far as I'm concerned, it's just that one dependency.  After I patched the FreeBSD port to bump it, the build worked.  You can check for yourself (assuming no cgo is needed):

    go get golang.org/x/sys@v0.6.0
    GOOS=freebsd GOARCH=riscv64 go build
