### ISSUE TITLE
CLI version 2.7.1 broken for Windows

### ISSUE THREAD

**Issue by Cparker96** [influxdata/influx-cli#497]
When downloading influxDB CLI version 2.7.1 zip folder for windows users, the file within the folder content is not defined as a .exe and cannot be executed. CLI version 2.6.1 is currently the most up to date version for windows users that works. 

Steps to reproduce:
1. Download CLI version here: https://docs.influxdata.com/influxdb/v2.7/tools/influx-cli/
2. Unzip content and add influx file to PATH env variable
3. open admin PS terminal and type 'influx help' or 'influx version'
4. Popup should occur prompting user to choose an app to open 'influx' with (this should not occur with a .exe file)

Broken file:
<img width="365" alt="broken file" src="https://user-images.githubusercontent.com/90932068/231235541-cfddb371-ea03-4181-89d5-f42a069ab238.png">

Corrected file with 2.6.1 version:
<img width="370" alt="image" src="https://user-images.githubusercontent.com/90932068/231235905-7a21a8e6-98be-4513-8311-14dc79f1bfbe.png">

**Comment by jeffreyssmith2nd** [comment]
Thanks for the report, I can confirm seeing this behavior. We'll investigate and get a fix out.

**Comment by jwyse** [comment]
Cparker96, the file is the correct executable, but is missing the .exe extension.  As a workaround, you can manually rename the extracted file from `influx` to `influx.exe`, or nudge Powershell to execute the file as-is by prefixing it: `.\influx version`

I agree that the better long-term fix would be for the release to contain an executable with the proper Windows extension, but this will get you going with the current 2.7.1 CLI.

**Comment by jeffreyssmith2nd** [comment]
This should be fixed in the 2.7.3 release. Please open a new issue if you encounter any further issues!
