### ISSUE TITLE
Port the `auth` command tree from `influxdb`

### ISSUE THREAD

**Issue by danxmoran** [influxdata/influx-cli#5]
Port the `auth` command (and any subcommands) from the `influxdb` repo.
* Replace the use of any hand-rolled HTTP clients with code-generated clients
* Interesting business logic should "live" outside of the `cmd/` module
* Tests should also be ported / extended as part of this

**Comment by wbaker85** [comment]
I filed an issue in `influxdb` that might be related to this one: https://github.com/influxdata/influxdb/issues/21607
