### ISSUE TITLE
CLI v2.7.1 for Windows is not an executable

### ISSUE THREAD

**Issue by mmustardlitmus** [influxdata/influx-cli#512]
CLI v2.7.1 for Windows is downloaded as a "file", not an executable. 

This results is InfluxDB CLI v2.7.1 not running in PowerShell:

<img width="583" alt="image" src="https://github.com/influxdata/influx-cli/assets/117295003/48120100-9e32-486b-ac51-a32541b0ffe0">

I compared the download with CLI v2.6.1:

![image](https://github.com/influxdata/influx-cli/assets/117295003/047c02cd-cdc1-4503-817a-88a2ae1cabe3)

Workaround: I downloaded and configured v2.6 and CLI v2.6.1 which work as expected.

**Comment by jeffreyssmith2nd** [comment]
This was addressed in the 2.7.3 release. Please let us know if there are any remaining issues in that release.

**Comment by mmustardlitmus** [comment]
Hi @jeffreyssmith2nd

**Comment by jeffreyssmith2nd** [comment]
@mmustardlitmus Thanks, I had missed a PR I needed to merge. The docs should be updated now.
