### ISSUE TITLE
CLI: list members of an org shows nil

### ISSUE THREAD

**Issue by russorat** [influxdata/influx-cli#71]
After creating a new user for an organization `influx user create -o influxdata -u new_russ -p something` and then listing the members of the org, i see a `<nil>` displayed in the username, even though it is returned when i print as json.

```
➜  influxdb git:(master) ✗ ./bin/darwin/influx org members list -n influxdata
ID			Name	User Type	Status
0673b0f2e540a000	<nil>	member		active
➜  influxdb git:(master) ✗
➜  influxdb git:(master) ✗ ./bin/darwin/influx org members list -n influxdata --json
[
	{
		"id": "0673b0f2e540a000",
		"name": "new_russ",
		"status": "active"
	}
]
```

might be related to something here: https://github.com/influxdata/influxdb/blob/master/cmd/influx/organization.go#L606

**Comment by danxmoran** [comment]
Seems to have been fixed in the latest CLI release, closing
