### ISSUE TITLE
Can only see 20 buckets in the CLI with `influx bucket list`

### ISSUE THREAD

**Issue by docmerlin** [influxdata/influx-cli#72]
This can be reproduced with:

```go
 for ((i=1;i<=200;i++));                         
do
   ./influx bucket create -n"bucket$i"
done
./influx bucket list --hide-headers|wc
```

This will produce 20 buckets.

**Comment by will-influxdata** [comment]
@danatinflux 
Could really use this as a parameter for the netreo migration(https://github.com/influxdata/InfluxDB-Cloud-2-Migration/issues/19)They have 36 customers and 5 buckets for each. I use the customer id in the bucket name. For token and dbrp processing on the scripts, I do a bucket list, grep out the buckets and then process them. Now I get clipped at 20. You should be able to specify something like --size 500
